"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "hi";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.about": "About Us",
    "nav.services": "Services",
    "nav.gallery": "Gallery",
    "nav.contact": "Contact",
    "nav.donate": "Donate Now",
    "nav.regNo": "Reg No: 1875",
    "nav.welcome": "Welcome to Annapurna Mahabahu Sewa Sangh",
    "hero.title": "Annapurna Mahabahu Sewa Sangh",
    "hero.subtitle": "Sewa Sangh",
    "hero.welcome": "Welcome to Annapurna Mahabahu Sewa",
    "hero.titleLine1": "Service to",
    "hero.titleLine2": "Humanity",
    "hero.titleLine3": "is the Greatest Duty",
    "hero.description": "Transforming lives through compassion. We are a community-driven initiative dedicated to feeding the hungry and empowering the weak.",
    "hero.donate": "Donate Now",
    "hero.learnMore": "Learn More",
    "hero.stats.lives": "Lives Impacted",
    "hero.stats.volunteers": "Volunteers",
    "hero.stats.projects": "Projects",
    "hero.stats.districts": "Districts",
    "stats.realImpact": "Real Impact",
    "stats.title1": "Numbers that Tell",
    "stats.title2": "Our",
    "stats.title3": "Selfless Journey",
    "stats.successfulProjects": "Successful Projects",
    "stats.serviceDistricts": "Service Districts",
    "activities.heading": "Impactful Initiatives",
    "activities.title1": "Our",
    "activities.title2": "Activities",
    "activities.learnMore": "Learn More",
    "activities.jalSeva.title": "Jal Seva",
    "activities.jalSeva.desc": "Providing clean drinking water to people during extreme heat conditions. Our volunteers work tirelessly to ensure hydration for the needy.",
    "activities.ganeshPuja.title": "Ganesh Puja",
    "activities.ganeshPuja.desc": "Organizing religious events to promote unity and cultural values. We believe in the power of spiritual gathering and community harmony.",
    "activities.vriddhashram.title": "Vriddhashram Seva",
    "activities.vriddhashram.desc": "Supporting and spending time with elderly people in old age homes. We provide compassion, care, and essentials for a dignified life.",
    "activities.bhandara.title": "Bhandara Seva",
    "activities.bhandara.desc": "Distributing free meals to the needy and underprivileged. No one should go to sleep hungry in our society.",
    "activities.plantation.title": "Plantation Drive",
    "activities.plantation.desc": "Promoting environmental awareness through tree plantation campaigns. We are committed to a greener future for the next generation.",
    "activities.blood.title": "Blood Donation",
    "activities.blood.desc": "Organizing blood donation camps to save lives. A single unit of blood can save multiple lives in emergencies.",
    "activities.murti.title": "Murti Visarjan Seva",
    "activities.murti.desc": "Assisting in religious activities with proper management and care. We ensure eco-friendly practices and social order.",
    "activities.harmony.title": "Social Harmony",
    "activities.harmony.desc": "Encouraging unity, equality, and harmony in society. Our campaigns focus on breaking barriers and fostering brotherhood.",
    "about.story": "Our Story",
    "about.dedicatedTitle1": "Dedicated to Serving",
    "about.dedicatedTitle2": "Humanity",
    "about.dedicatedTitle3": "and Growth",
    "about.storyDesc": "We are a non-profit organization dedicated to serving humanity and uplifting underprivileged communities. Our mission is to bring positive change in society by helping those who need support the most.",
    "about.yearsExp": "Years Experience",
    "about.activeMembers": "Active Members",
    "about.trustedNGO": "Trusted NGO",
    "about.estd": "ESTD. 2014",
    "about.identity": "Identity",
    "about.whoWeAre": "Who We Are",
    "about.whoWeAreDesc1": "We are a group of individuals united by a common goal — to make the world a better place. Our organization focuses on spreading love, care, and support to every section of society without discrimination.",
    "about.whoWeAreDesc2": "We aim to build a strong community where people help each other grow and live with dignity. With a team of passionate volunteers and dedicated members, we work tirelessly in various social dimensions.",
    "about.whatWeDo": "What We Do",
    "about.whatWeDo1": "Providing Food & Clean Water",
    "about.whatWeDo2": "Organizing Blood Camps",
    "about.whatWeDo3": "Supporting Old Age Homes",
    "about.whatWeDo4": "Tree Plantation Drives",
    "about.whatWeDo5": "Social Harmony & Unity",
    "about.whatWeDo6": "Cultural Service Activities",
    "about.mission": "Our Mission",
    "about.missionDesc": "Our mission is to serve humanity selflessly and ensure that no one in society is left behind. We strive to bring hope, support, and happiness to every life we touch.",
    "about.vision": "Our Vision",
    "about.visionDesc": "Our vision is to create a world where everyone has access to basic necessities like food, education, healthcare, and lives a life of dignity and respect.",
    "about.philosophy": "Philosophy",
    "about.values": "Our Values",
    "about.value1": "Compassion & Humanity",
    "about.value2": "Transparency & Trust",
    "about.value3": "Dedication to Service",
    "about.value4": "Equality & Respect",
    "about.coreFoundation": "Core Foundation",
    "about.ctaTitle": "Empower Change With Us",
    "about.ctaDesc": "Your dedication fuels our mission. Together, we can create a world where everyone lives with dignity.",
    "about.joinMovement": "Join the Movement",
    "about.beVolunteer": "Be a Volunteer",
    "about.transparent": "TRANSPARENT",
    "about.impactful": "IMPACTFUL",
    "about.dedicated": "DEDICATED",
    "about.communityDriven": "COMMUNITY-DRIVEN",
    "about.readyImpact": "Ready to Make a Real Impact?",
    "about.readyDesc": "Join Annapurna Mahabahu Sewa Sangh in our mission to uplift the underprivileged. Your support helps us bring hope and dignity to those in need.",
    "about.callUs": "Call Us Now",
    "about.whatsApp": "WhatsApp Us",
    "services.commitment": "OUR COMMITMENT TO HUMANITY",
    "services.title1": "Our Professional",
    "services.title2": "Services",
    "services.quote": "\"Driven by compassion and guided by service, we work tirelessly to bridge the gap between basic needs and a dignified life for every individual in our society.\"",
    "services.s1.title": "Life-Saving Blood Donation Camps",
    "services.s1.desc": "We bridge the gap between donors and patients by organizing regular blood donation drives, ensuring local hospitals have a steady supply of life-saving resources for medical emergencies.",
    "services.s2.title": "Nutritional Support (Bhandara Seva)",
    "services.s2.desc": "Combating hunger through our large-scale food distribution programs, where we serve fresh, hygienic, and nutritious meals to thousands of underprivileged individuals every week.",
    "services.s3.title": "Hospital & Emergency Relief",
    "services.s3.desc": "Providing immediate medical assistance and support to patients and their families at major healthcare centers, ensuring they have the care and resources needed during crises.",
    "services.s4.title": "Elderly Care & Dignity (Vriddhashram)",
    "services.s4.desc": "Providing companionship and essential support to residents of old age homes, fostering an environment of love, respect, and emotional well-being for our senior citizens.",
    "services.s5.title": "Social Empowerment & Awareness",
    "services.s5.desc": "Advocating for equality and justice through awareness campaigns and grassroots initiatives that empower the marginalized and promote peace within our diverse society.",
    "services.s6.title": "Cultural & Spiritual Unity",
    "services.s6.desc": "Fostering social cohesion and preserving our rich heritage by organizing and supporting religious events such as Ganesh Puja, promoting universal values and communal harmony.",
    "services.s7.title": "Community Outreach Programs",
    "services.s7.desc": "Expanding our reach into local communities to identify and address immediate needs, providing customized assistance and resources to families in underserved areas.",
    "services.s8.title": "Pure Water Initiative (Jal Seva)",
    "services.s8.desc": "Dedicated to providing life-sustaining clean drinking water to communities, especially during the peak of summer, ensuring no one suffers from thirst in the face of extreme conditions.",
    "services.s9.title": "Essential Distribution Drives",
    "services.s9.desc": "Organizing systematic distribution of basic necessities, including clothing, hygiene kits, and seasonal essentials, to ensure the well-being of the most vulnerable sections of society.",
    "services.s10.title": "Environmental Sustainability",
    "services.s10.desc": "Leading the charge for a greener future through extensive tree plantation drives and ecological awareness programs, aimed at restoring our natural environment for future generations.",
    "services.coreImpact": "Core Impact",
    "gallery.capturedMoments": "Captured Moments",
    "gallery.title1": "Our",
    "gallery.title2": "Gallery",
    "gallery.desc": "A glimpse into our journey of selfless service and community impact through photos.",
    "gallery.cat.all": "All",
    "gallery.cat.service": "Service",
    "gallery.cat.events": "Events",
    "gallery.cat.charity": "Charity",
    "gallery.cat.nature": "Nature",
    "gallery.img1.title": "Jal Sewa Campaign",
    "gallery.img2.title": "Cultural Unity",
    "gallery.img3.title": "Support for Elders",
    "gallery.img4.title": "Food Distribution",
    "gallery.img5.title": "Green Environment",
    "gallery.img6.title": "Blood Donation Camp",
    "gallery.img7.title": "Religious Service",
    "gallery.img8.title": "Community Harmony",
    "gallery.img9.title": "Community Gathering",
    "gallery.img10.title": "Education Support",
    "gallery.img11.title": "Health Awareness",
    "contact.getInTouch": "Get In Touch",
    "contact.title1": "Contact",
    "contact.title2": "Us",
    "contact.desc": "Have questions or want to join our mission? Reach out to us, and we'll be happy to connect.",
    "contact.info": "Contact Information",
    "contact.phone": "Call Us",
    "contact.phoneSub": "Mon-Sat 9am to 6pm",
    "contact.email": "Email Us",
    "contact.emailSub": "We'll reply within 24h",
    "contact.address": "Visit Us",
    "contact.addressVal": "750 Chirag Delhi, Delhi",
    "contact.addressSub": "New Delhi, 110017",
    "contact.follow": "Follow Our Journey",
    "contact.hours": "Operational Hours",
    "contact.hoursSub": "Available 24/7 for Emergency",
    "contact.sendMsg": "Send us a Message",
    "contact.name": "Full Name",
    "contact.namePlaceholder": "Your Name",
    "contact.emailLabel": "Email Address",
    "contact.emailPlaceholder": "email@example.com",
    "contact.help": "How can we help?",
    "contact.msg": "Your Message",
    "contact.msgPlaceholder": "Write your message here...",
    "contact.send": "Send Message",
    "contact.sending": "Sending...",
    "contact.sent": "Message Sent!",
    "contact.failed": "Failed to send message. Please try again.",
    "contact.successToast": "Thank you! Your message has been sent successfully.",
    "contact.type.general": "General Inquiry",
    "contact.type.donation": "Donation Information",
    "contact.type.volunteer": "Volunteer Opportunity",
    "contact.type.report": "Report a Need",
    "donate.supportCause": "Support Our Cause",
    "donate.title1": "Every Act of",
    "donate.title2": "Generosity",
    "donate.title3": "Counts",
    "donate.quote": "\"Your gift provides the foundation for our programs and helps us reach thousands of people in need.\"",
    "donate.scanToPay": "Scan to Pay",
    "donate.trustedGateway": "Trusted Payment Gateway",
    "donate.bankDetails": "Bank Transfer",
    "donate.bankDetailsItalic": "Details",
    "donate.accName": "Account Name",
    "donate.bankName": "Bank Name",
    "donate.accNum": "Account Number",
    "donate.ifsc": "IFSC Code",
    "donate.branch": "Branch",
    "donate.whatsappHint": "Send transaction screenshot on WhatsApp for instant donation receipt.",
    "donate.haveQuestions": "Have Any",
    "donate.questionsItalic": "Questions?",
    "donate.teamHelp": "Whether you want to know about our impact, join as a volunteer, or need support, our team is here to help you.",
    "donate.callEnquiry": "Call Enquiry",
    "donate.emailSupport": "Email Support",
    "donate.formTitle": "Send Your Message",
    "donate.placeholderName": "Your name here",
    "donate.placeholderEmail": "example@mail.com",
    "donate.placeholderMsg": "Type your message...",
    "donate.successToast": "Thank you! Your donation enquiry has been received.",
    "donate.regInfo": "GOVT RECOGNIZED REGISTRATION: IV/999/2024-DELHI",
    "donate.since": "\"Committed to serving humanity since 2014\"",
    "donate.copy": "Copy",
    "donate.copied": "Copied",
    "footer.desc": "\"Annapurna Mahabahu Sewa Sangh\" is a charitable organization dedicated to helping poor and underprivileged people. Service to humanity is our ultimate goal.",
    "footer.quickLinks": "Quick Links",
    "footer.support": "Support",
    "footer.mission": "Our Mission",
    "footer.stories": "Success Stories",
    "footer.faqs": "FAQs",
    "footer.rights": "All Rights Reserved.",
    "footer.designed": "Designed & Developed by",
  },
  hi: {
    "nav.home": "होम",
    "nav.about": "हमारे बारे में",
    "nav.services": "सेवाएं",
    "nav.gallery": "गैलरी",
    "nav.contact": "संपर्क करें",
    "nav.donate": "अभी दान करें",
    "nav.regNo": "रजि. नंबर: 1875",
    "nav.welcome": "अन्नपूर्णा महाबाहु सेवा संघ में आपका स्वागत है",
    "hero.title": "अन्नपूर्णा महाबाहु सेवा संघ",
    "hero.subtitle": "सेवा संघ",
    "hero.welcome": "अन्नपूर्णा महाबाहु सेवा में आपका स्वागत है",
    "hero.titleLine1": "मानवता की",
    "hero.titleLine2": "सेवा ही",
    "hero.titleLine3": "सबसे बड़ा कर्तव्य है",
    "hero.description": "करुणा के माध्यम से जीवन बदलना। हम एक समुदाय-संचालित पहल हैं जो भूखों को खिलाने और कमजोरों को सशक्त बनाने के लिए समर्पित हैं।",
    "hero.donate": "अभी दान करें",
    "hero.learnMore": "अधिक जानें",
    "hero.stats.lives": "प्रभावित जीवन",
    "hero.stats.volunteers": "स्वयंसेवक",
    "hero.stats.projects": "परियोजनाएं",
    "hero.stats.districts": "जिले",
    "stats.realImpact": "वास्तविक प्रभाव",
    "stats.title1": "संख्याएं जो बताती हैं",
    "stats.title2": "हमारी",
    "stats.title3": "निस्वार्थ यात्रा",
    "stats.successfulProjects": "सफल परियोजनाएं",
    "stats.serviceDistricts": "सेवा जिले",
    "activities.heading": "प्रभावशाली पहल",
    "activities.title1": "हमारी",
    "activities.title2": "गतिविधियां",
    "activities.learnMore": "अधिक जानें",
    "activities.jalSeva.title": "जल सेवा",
    "activities.jalSeva.desc": "भीषण गर्मी की स्थिति में लोगों को स्वच्छ पेयजल उपलब्ध कराना। हमारे स्वयंसेवक जरूरतमंदों के लिए जलयोजन सुनिश्चित करने के लिए अथक प्रयास करते हैं।",
    "activities.ganeshPuja.title": "गणेश पूजा",
    "activities.ganeshPuja.desc": "एकता और सांस्कृतिक मूल्यों को बढ़ावा देने के लिए धार्मिक कार्यक्रमों का आयोजन। हम आध्यात्मिक मिलन और सामुदायिक सद्भाव की शक्ति में विश्वास करते हैं।",
    "activities.vriddhashram.title": "वृद्धाश्रम सेवा",
    "activities.vriddhashram.desc": "वृद्धाश्रमों में बुजुर्ग लोगों के साथ समय बिताना और उनका समर्थन करना। हम एक गरिमापूर्ण जीवन के लिए करुणा, देखभाल और आवश्यक वस्तुएं प्रदान करते हैं।",
    "activities.bhandara.title": "भंडारा सेवा",
    "activities.bhandara.desc": "जरूरतमंदों और वंचितों को मुफ्त भोजन वितरित करना। हमारे समाज में कोई भी भूखा नहीं सोना चाहिए।",
    "activities.plantation.title": "वृक्षारोपण अभियान",
    "activities.plantation.desc": "वृक्षारोपण अभियानों के माध्यम से पर्यावरण जागरूकता को बढ़ावा देना। हम अगली पीढ़ी के लिए हरित भविष्य के लिए प्रतिबद्ध हैं।",
    "activities.blood.title": "रक्तदान",
    "activities.blood.desc": "जीवन बचाने के लिए रक्तदान शिविरों का आयोजन। रक्त की एक इकाई आपात स्थिति में कई जिंदगियां बचा सकती है।",
    "activities.murti.title": "मूर्ति विसर्जन सेवा",
    "activities.murti.desc": "उचित प्रबंधन और देखभाल के साथ धार्मिक गतिविधियों में सहायता करना। हम पर्यावरण के अनुकूल प्रथाओं और सामाजिक व्यवस्था सुनिश्चित करते।",
    "activities.harmony.title": "सामाजिक समरसता",
    "activities.harmony.desc": "समाज में एकता, समानता और सद्भाव को प्रोत्साहित करना। हमारे अभियान बाधाओं को तोड़ने और भाईचारे को बढ़ावा देने पर ध्यान केंद्रित करते हैं।",
    "about.story": "हमारी कहानी",
    "about.dedicatedTitle1": "मानवता की सेवा",
    "about.dedicatedTitle2": "और विकास",
    "about.dedicatedTitle3": "के लिए समर्पित",
    "about.storyDesc": "हम एक गैर-लाभकारी संगठन हैं जो मानवता की सेवा करने और वंचित समुदायों के उत्थान के लिए समर्पित हैं। हमारा मिशन समाज में उन लोगों की मदद करके सकारात्मक बदलाव लाना है जिन्हें सहायता की सबसे अधिक आवश्यकता है।",
    "about.yearsExp": "वर्षों का अनुभव",
    "about.activeMembers": "सक्रिय सदस्य",
    "about.trustedNGO": "विश्वसनीय एनजीओ",
    "about.estd": "स्थापना 2014",
    "about.identity": "पहचान",
    "about.whoWeAre": "हम कौन हैं",
    "about.whoWeAreDesc1": "हम एक साझा लक्ष्य से एकजुट व्यक्तियों का एक समूह हैं - दुनिया को एक बेहतर जगह बनाने के लिए। हमारा संगठन बिना किसी भेदभाव के समाज के हर वर्ग को प्यार, देखभाल और सहायता फैलाने पर ध्यान केंद्रित करता है।",
    "about.whoWeAreDesc2": "हमारा लक्ष्य एक मजबूत समुदाय बनाना है जहां लोग एक-दूसरे को बढ़ने और गरिमा के साथ जीने में मदद करें। भावुक स्वयंसेवकों और समर्पित सदस्यों की एक टीम के साथ, हम विभिन्न सामाजिक आयामों में अथक रूप से काम करते हैं।",
    "about.whatWeDo": "हम क्या करते हैं",
    "about.whatWeDo1": "भोजन और स्वच्छ पानी उपलब्ध कराना",
    "about.whatWeDo2": "रक्तदान शिविरों का आयोजन",
    "about.whatWeDo3": "वृद्धाश्रमों का समर्थन करना",
    "about.whatWeDo4": "वृक्षारोपण अभियान",
    "about.whatWeDo5": "सामाजिक समरसता और एकता",
    "about.whatWeDo6": "सांस्कृतिक सेवा गतिविधियां",
    "about.mission": "हमारा मिशन",
    "about.missionDesc": "हमारा मिशन मानवता की निस्वार्थ सेवा करना और यह सुनिश्चित करना है कि समाज में कोई भी पीछे न रहे। हम हर उस जीवन में आशा, समर्थन और खुशी लाने का प्रयास करते हैं जिसे हम छूते हैं।",
    "about.vision": "हमारा विजन",
    "about.visionDesc": "हमारा विजन एक ऐसी दुनिया बनाना है जहां हर किसी के पास भोजन, शिक्षा, स्वास्थ्य देखभाल जैसी बुनियादी जरूरतों तक पहुंच हो और वह गरिमा और सम्मान का जीवन जिए।",
    "about.philosophy": "दर्शन",
    "about.values": "हमारे मूल्य",
    "about.value1": "करुणा और मानवता",
    "about.value2": "पारदर्शिता और विश्वास",
    "about.value3": "सेवा के प्रति समर्पण",
    "about.value4": "समानता और सम्मान",
    "about.coreFoundation": "मुख्य आधार",
    "about.ctaTitle": "हमारे साथ बदलाव को सशक्त बनाएं",
    "about.ctaDesc": "आपका समर्पण हमारे मिशन को ऊर्जा देता है। साथ मिलकर, हम एक ऐसी दुनिया बना सकते हैं जहाँ हर कोई गरिमा के साथ रहता है।",
    "about.joinMovement": "आंदोलन में शामिल हों",
    "about.beVolunteer": "स्वयंसेवक बनें",
    "about.transparent": "पारदर्शी",
    "about.impactful": "प्रभावशाली",
    "about.dedicated": "समर्पित",
    "about.communityDriven": "समुदाय-संचालित",
    "about.readyImpact": "वास्तविक प्रभाव डालने के लिए तैयार हैं?",
    "about.readyDesc": "वंचितों के उत्थान के हमारे मिशन में अन्नपूर्णा महाबाहु सेवा संघ के साथ जुड़ें। आपका समर्थन हमें उन लोगों के लिए आशा और गरिमा लाने में मदद करता है जिन्हें इसकी आवश्यकता है।",
    "about.callUs": "हमें अभी कॉल करें",
    "about.whatsApp": "व्हाट्सएप करें",
    "services.commitment": "मानवता के प्रति हमारी प्रतिबद्धता",
    "services.title1": "हमारी पेशेवर",
    "services.title2": "सेवाएं",
    "services.quote": "\"करुणा से प्रेरित और सेवा द्वारा निर्देशित, हम अपने समाज के प्रत्येक व्यक्ति के लिए बुनियादी जरूरतों और गरिमापूर्ण जीवन के बीच की खाई को पाटने के लिए अथक प्रयास करते हैं।\"",
    "services.s1.title": "जीवन रक्षक रक्तदान शिविर",
    "services.s1.desc": "हम नियमित रक्तदान अभियान आयोजित करके दाताओं और रोगियों के बीच की खाई को पाटते हैं, यह सुनिश्चित करते हैं कि स्थानीय अस्पतालों में चिकित्सा आपात स्थितियों के लिए जीवन रक्षक संसाधनों की निरंतर आपूर्ति हो।",
    "services.s2.title": "पोषण संबंधी सहायता (भंडारा सेवा)",
    "services.s2.desc": "हमारे बड़े पैमाने पर भोजन वितरण कार्यक्रमों के माध्यम से भूख का मुकाबला करना, जहां हम हर हफ्ते हजारों वंचित व्यक्तियों को ताजा, स्वच्छ और पौष्टिक भोजन परोसते हैं।",
    "services.s3.title": "अस्पताल और आपातकालीन राहत",
    "services.s3.desc": "प्रमुख स्वास्थ्य केंद्रों पर रोगियों और उनके परिवारों को तत्काल चिकित्सा सहायता और सहायता प्रदान करना, यह सुनिश्चित करना कि उनके पास संकट के दौरान आवश्यक देखभाल और संसाधन हों।",
    "services.s4.title": "बुजुर्गों की देखभाल और गरिमा (वृद्धाश्रम)",
    "services.s4.desc": "वृद्धाश्रमों के निवासियों को साथ और आवश्यक सहायता प्रदान करना, हमारे वरिष्ठ नागरिकों के लिए प्यार, सम्मान और भावनात्मक कल्याण का वातावरण बनाना।",
    "services.s5.title": "सामाजिक अधिकारिता और जागरूकता",
    "services.s5.desc": "जागरूकता अभियानों और जमीनी स्तर की पहलों के माध्यम से समानता और न्याय की वकालत करना जो हाशिए पर रहने वालों को सशक्त बनाते हैं और हमारे विविध समाज के भीतर शांति को बढ़ावा देते हैं।",
    "services.s6.title": "सांस्कृतिक और आध्यात्मिक एकता",
    "services.s6.desc": "गणेश पूजा जैसे धार्मिक कार्यक्रमों के आयोजन और समर्थन करके सामाजिक सामंजस्य को बढ़ावा देना और हमारी समृद्ध विरासत को संरक्षित करना, सार्वभौमिक मूल्यों और सांप्रदायिक सद्भाव को बढ़ावा देना।",
    "services.s7.title": "सामुदायिक आउटरीच कार्यक्रम",
    "services.s7.desc": "तत्काल जरूरतों की पहचान करने और उन्हें संबोधित करने के लिए स्थानीय समुदायों में अपनी पहुंच का विस्तार करना, वंचित क्षेत्रों में परिवारों को अनुकूलित सहायता और संसाधन प्रदान करना।",
    "services.s8.title": "शुद्ध जल पहल (जल सेवा)",
    "services.s8.desc": "समुदायों को जीवनदायी स्वच्छ पेयजल प्रदान करने के लिए समर्पित, विशेष रूप से गर्मी के चरम के दौरान, यह सुनिश्चित करना कि चरम स्थितियों के बावजूद कोई प्यास से न जूझे।",
    "services.s9.title": "आवश्यक वितरण अभियान",
    "services.s9.desc": "समाज के सबसे कमजोर वर्गों की भलाई सुनिश्चित करने के लिए कपड़े, स्वच्छता किट और मौसमी आवश्यक वस्तुओं सहित बुनियादी जरूरतों के व्यवस्थित वितरण का आयोजन।",
    "services.s10.title": "पर्यावरण स्थिरता",
    "services.s10.desc": "व्यापक वृक्षारोपण अभियानों और पारिस्थितिक जागरूकता कार्यक्रमों के माध्यम से एक हरित भविष्य का नेतृत्व करना, जिसका उद्देश्य भावी पीढ़ियों के लिए हमारे प्राकृतिक पर्यावरण को बहाल करना है।",
    "services.coreImpact": "मुख्य प्रभाव",
    "gallery.capturedMoments": "कैप्चर किए गए पल",
    "gallery.title1": "हमारी",
    "gallery.title2": "गैलरी",
    "gallery.desc": "तस्वीरों के माध्यम से हमारी निस्वार्थ सेवा और सामुदायिक प्रभाव की यात्रा की एक झलक।",
    "gallery.cat.all": "सभी",
    "gallery.cat.service": "सेवा",
    "gallery.cat.events": "कार्यक्रम",
    "gallery.cat.charity": "दान",
    "gallery.cat.nature": "प्रकृति",
    "gallery.img1.title": "जल सेवा अभियान",
    "gallery.img2.title": "सांस्कृतिक एकता",
    "gallery.img3.title": "बुजुर्गों के लिए सहायता",
    "gallery.img4.title": "भोजन वितरण",
    "gallery.img5.title": "हरित पर्यावरण",
    "gallery.img6.title": "रक्तदान शिविर",
    "gallery.img7.title": "धार्मिक सेवा",
    "gallery.img8.title": "सामुदायिक सद्भाव",
    "gallery.img9.title": "सामुदायिक सभा",
    "gallery.img10.title": "शिक्षा सहायता",
    "gallery.img11.title": "स्वास्थ्य जागरूकता",
    "contact.getInTouch": "संपर्क में रहें",
    "contact.title1": "हमसे",
    "contact.title2": "संपर्क करें",
    "contact.desc": "क्या आपके पास प्रश्न हैं या आप हमारे मिशन में शामिल होना चाहते हैं? हमसे संपर्क करें, और हमें जुड़ने में खुशी होगी।",
    "contact.info": "संपर्क जानकारी",
    "contact.phone": "हमें कॉल करें",
    "contact.phoneSub": "सोम-शनि सुबह 9 बजे से शाम 6 बजे तक",
    "contact.email": "हमें ईमेल करें",
    "contact.emailSub": "हम 24 घंटे के भीतर जवाब देंगे",
    "contact.address": "हमसे मिलें",
    "contact.addressVal": "750 चिराग दिल्ली, दिल्ली",
    "contact.addressSub": "नई दिल्ली, 110017",
    "contact.follow": "हमारी यात्रा का अनुसरण करें",
    "contact.hours": "परिचालन घंटे",
    "contact.hoursSub": "आपातकाल के लिए 24/7 उपलब्ध",
    "contact.sendMsg": "हमें एक संदेश भेजें",
    "contact.name": "पूरा नाम",
    "contact.namePlaceholder": "आपका नाम",
    "contact.emailLabel": "ईमेल पता",
    "contact.emailPlaceholder": "email@example.com",
    "contact.help": "हम आपकी किस प्रकार सहायता कर सकते हैं?",
    "contact.msg": "आपका संदेश",
    "contact.msgPlaceholder": "अपना संदेश यहाँ लिखें...",
    "contact.send": "संदेश भेजें",
    "contact.sending": "भेजा जा रहा है...",
    "contact.sent": "संदेश भेज दिया गया!",
    "contact.failed": "संदेश भेजने में विफल। कृपया पुन: प्रयास करें।",
    "contact.successToast": "धन्यवाद! आपका संदेश सफलतापूर्वक भेज दिया गया है।",
    "contact.type.general": "सामान्य पूछताछ",
    "contact.type.donation": "दान की जानकारी",
    "contact.type.volunteer": "स्वयंसेवक अवसर",
    "contact.type.report": "जरूरत की रिपोर्ट करें",
    "donate.supportCause": "हमारे उद्देश्य का समर्थन करें",
    "donate.title1": "उदारता का",
    "donate.title2": "हर कार्य",
    "donate.title3": "मेन रखता है",
    "donate.quote": "\"आपका उपहार हमारे कार्यक्रमों के लिए आधार प्रदान करता है और हमें हजारों जरूरतमंद लोगों तक पहुंचने में मदद करता है।\"",
    "donate.scanToPay": "भुगतान करने के लिए स्कैन करें",
    "donate.trustedGateway": "विश्वसनीय भुगतान गेटवे",
    "donate.bankDetails": "बैंक हस्तांतरण",
    "donate.bankDetailsItalic": "विवरण",
    "donate.accName": "खाता नाम",
    "donate.bankName": "बैंक का नाम",
    "donate.accNum": "खाता संख्या",
    "donate.ifsc": "आईएफएससी कोड",
    "donate.branch": "शाखा",
    "donate.whatsappHint": "तत्काल दान रसीद के लिए व्हाट्सएप पर लेनदेन का स्क्रीनशॉट भेजें।",
    "donate.haveQuestions": "क्या आपके पास कोई",
    "donate.questionsItalic": "प्रश्न हैं?",
    "donate.teamHelp": "चाहे आप हमारे प्रभाव के बारे में जानना चाहते हों, स्वयंसेवक के रूप में शामिल होना चाहते हों, या सहायता की आवश्यकता हो, हमारी टीम आपकी मदद के लिए यहाँ है।",
    "donate.callEnquiry": "कॉल पूछताछ",
    "donate.emailSupport": "ईमेल सहायता",
    "donate.formTitle": "अपना संदेश भेजें",
    "donate.placeholderName": "आपका नाम यहाँ",
    "donate.placeholderEmail": "example@mail.com",
    "donate.placeholderMsg": "अपना संदेश टाइप करें...",
    "donate.successToast": "धन्यवाद! आपकी दान पूछताछ प्राप्त हो गई है।",
    "donate.regInfo": "सरकारी मान्यता प्राप्त पंजीकरण: IV/999/2024-DELHI",
    "donate.since": "\"2014 से मानवता की सेवा के लिए प्रतिबद्ध\"",
    "donate.copy": "कॉपी करें",
    "donate.copied": "कॉपी हो गया",
    "footer.desc": "\"अन्नपूर्णा महाबाहु सेवा संघ\" एक धर्मार्थ संगठन है जो गरीब और वंचित लोगों की मदद के लिए समर्पित है। मानवता की सेवा ही हमारा अंतिम लक्ष्य है।",
    "footer.quickLinks": "त्वरित लिंक",
    "footer.support": "सहायता",
    "footer.mission": "हमारा मिशन",
    "footer.stories": "सफलता की कहानियां",
    "footer.faqs": "अक्सर पूछे जाने वाले प्रश्न",
    "footer.rights": "सर्वाधिकार सुरक्षित।",
    "footer.designed": "डिजाइन और विकसित द्वारा",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const savedLang = localStorage.getItem("language") as Language;
    if (savedLang && (savedLang === "en" || savedLang === "hi")) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
    document.documentElement.lang = lang;
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
